# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update
    - apt -y install cmake
    - apt -y install libfmt-dev
    - apt update
  script:
    - cd OhGodMakeThePunsStop_version_2
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" ..
    - make
  artifacts:
    paths:
      - ./OhGodMakeThePunsStop_version_2